/** Acts / Rules / Forms repository + quick links. EDITABLE; links point to the
 * relevant official source root. Names follow the firm's requested catalogue
 * (Book1, Knowledge Bank #37-40). Deep links to specific instruments are to be
 * confirmed by the firm. */
export interface RepoItem {
  category: string;
  name: string;
  link: string; // official source (root) or placeholder
}


export const acts: RepoItem[] = [
  { category: "Direct Tax", name: "Direct Tax Code, 2025", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Income-tax Act, 1961", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Black Money (Undisclosed Foreign Income and Assets) and Imposition of Tax Act, 2015", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Benami Transactions (Prohibition) Act, 1988", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Equalisation Levy Provisions", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Direct Tax Vivad se Vishwas Provisions", link: "https://incometaxindia.gov.in/" },
  { category: "GST & Indirect Tax", name: "Central Goods and Services Tax Act, 2017", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Integrated Goods and Services Tax Act, 2017", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Union Territory Goods and Services Tax Act, 2017", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "GST (Compensation to States) Act, 2017", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Customs Act, 1962", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Customs Tariff Act, 1975", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Customs Brokers Licensing Regulations", link: "https://cbic-gst.gov.in/" },
  { category: "Corporate & Commercial", name: "Companies Act, 2013", link: "https://www.mca.gov.in/" },
  { category: "Corporate & Commercial", name: "Limited Liability Partnership Act, 2008", link: "https://www.mca.gov.in/" },
  { category: "Corporate & Commercial", name: "Partnership Act, 1932", link: "https://www.mca.gov.in/" },
  { category: "Corporate & Commercial", name: "Indian Contract Act, 1872", link: "https://www.mca.gov.in/" },
  { category: "Corporate & Commercial", name: "Sale of Goods Act, 1930", link: "https://www.mca.gov.in/" },
  { category: "Corporate & Commercial", name: "Specific Relief Act, 1963", link: "https://www.mca.gov.in/" },
  { category: "Corporate & Commercial", name: "Competition Act, 2002", link: "https://www.mca.gov.in/" },
  { category: "FEMA, RBI & Cross-Border", name: "Foreign Exchange Management Act, 1999", link: "https://www.rbi.org.in/" },
  { category: "FEMA, RBI & Cross-Border", name: "Foreign Contribution (Regulation) Act, 2010", link: "https://www.rbi.org.in/" },
  { category: "FEMA, RBI & Cross-Border", name: "Reserve Bank of India Act, 1934", link: "https://www.rbi.org.in/" },
  { category: "FEMA, RBI & Cross-Border", name: "Banking Regulation Act, 1949", link: "https://www.rbi.org.in/" },
  { category: "FEMA, RBI & Cross-Border", name: "Payment and Settlement Systems Act, 2007", link: "https://www.rbi.org.in/" },
  { category: "FEMA, RBI & Cross-Border", name: "Overseas Investment Rules & Regulations, 2022", link: "https://www.rbi.org.in/" },
  { category: "FEMA, RBI & Cross-Border", name: "Foreign Exchange Management (Non-Debt Instruments) Rules, 2019", link: "https://www.rbi.org.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI Act, 1992", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "Securities Contracts (Regulation) Act, 1956", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "Depositories Act, 1996", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI (LODR) Regulations, 2015", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI (AIF) Regulations, 2012", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI (Portfolio Managers) Regulations, 2020", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI (Investment Advisers) Regulations, 2013", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI (Research Analysts) Regulations, 2014", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI (PIT) Regulations, 2015", link: "https://www.sebi.gov.in/" },
  { category: "SEBI & Capital Markets", name: "SEBI (SAST) Regulations, 2011", link: "https://www.sebi.gov.in/" },
  { category: "Insolvency & Restructuring", name: "Insolvency and Bankruptcy Code, 2016", link: "https://www.ibbi.gov.in/" },
  { category: "Insolvency & Restructuring", name: "IBBI (Insolvency Resolution Process) Regulations", link: "https://www.ibbi.gov.in/" },
  { category: "Insolvency & Restructuring", name: "IBBI (Liquidation Process) Regulations", link: "https://www.ibbi.gov.in/" },
  { category: "Insolvency & Restructuring", name: "IBBI (Valuation) Rules", link: "https://www.ibbi.gov.in/" },
  { category: "Trusts, NGOs & CSR", name: "Indian Trusts Act, 1882", link: "https://www.mca.gov.in/" },
  { category: "Trusts, NGOs & CSR", name: "Societies Registration Act, 1860", link: "https://www.mca.gov.in/" },
  { category: "Trusts, NGOs & CSR", name: "Foreign Contribution (Regulation) Act, 2010 — NGO", link: "https://www.mca.gov.in/" },
  { category: "Trusts, NGOs & CSR", name: "CSR Provisions under Companies Act, 2013", link: "https://www.mca.gov.in/" },
  { category: "Labour & Employment", name: "Code on Wages, 2019", link: "https://labour.gov.in/" },
  { category: "Labour & Employment", name: "Industrial Relations Code, 2020", link: "https://labour.gov.in/" },
  { category: "Labour & Employment", name: "Code on Social Security, 2020", link: "https://labour.gov.in/" },
  { category: "Labour & Employment", name: "Occupational Safety, Health and Working Conditions Code, 2020", link: "https://labour.gov.in/" },
  { category: "Labour & Employment", name: "Employees' Provident Funds and Miscellaneous Provisions Act, 1952", link: "https://labour.gov.in/" },
  { category: "Labour & Employment", name: "Employees' State Insurance Act, 1948", link: "https://labour.gov.in/" },
  { category: "Labour & Employment", name: "Payment of Gratuity Act, 1972", link: "https://labour.gov.in/" },
  { category: "Labour & Employment", name: "POSH Act, 2013", link: "https://labour.gov.in/" },
  { category: "Fintech, NBFC & Financial Services", name: "NBFC Master Directions", link: "https://www.rbi.org.in/" },
  { category: "Fintech, NBFC & Financial Services", name: "Account Aggregator Framework", link: "https://www.rbi.org.in/" },
  { category: "Fintech, NBFC & Financial Services", name: "Payment Aggregator Guidelines", link: "https://www.rbi.org.in/" },
  { category: "Fintech, NBFC & Financial Services", name: "Prevention of Money Laundering Act, 2002", link: "https://www.rbi.org.in/" },
  { category: "Intellectual Property", name: "Trade Marks Act, 1999", link: "https://ipindia.gov.in/" },
  { category: "Intellectual Property", name: "Patents Act, 1970", link: "https://ipindia.gov.in/" },
  { category: "Intellectual Property", name: "Copyright Act, 1957", link: "https://ipindia.gov.in/" },
  { category: "Intellectual Property", name: "Designs Act, 2000", link: "https://ipindia.gov.in/" },
  { category: "Digital & Technology", name: "Digital Personal Data Protection Act, 2023", link: "https://www.meity.gov.in/" },
  { category: "Digital & Technology", name: "Information Technology Act, 2000", link: "https://www.meity.gov.in/" },
];

export const rules: RepoItem[] = [
  { category: "Direct Tax", name: "Income-tax Rules, 1962", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Income Computation and Disclosure Standards (ICDS)", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Safe Harbour Rules", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Faceless Assessment Scheme", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "Faceless Appeal Scheme", link: "https://incometaxindia.gov.in/" },
  { category: "Direct Tax", name: "General Anti-Avoidance Rules (GAAR)", link: "https://incometaxindia.gov.in/" },
  { category: "GST & Indirect Tax", name: "CGST Rules, 2017", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "IGST Rules, 2017", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "GST Refund Rules", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "GST E-Invoice Framework", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "GST E-Way Bill Rules", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Customs Valuation Rules, 2007", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Customs Tariff Rules", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Customs Brokers Licensing Regulations, 2018", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "RoDTEP Scheme Guidelines", link: "https://cbic-gst.gov.in/" },
  { category: "GST & Indirect Tax", name: "Foreign Trade Policy 2023", link: "https://cbic-gst.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Incorporation) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Management and Administration) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Accounts) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Audit and Auditors) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Appointment and Qualification of Directors) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Share Capital and Debentures) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Prospectus and Allotment of Securities) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (Compromises, Arrangements and Amalgamations) Rules, 2016", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "Companies (CSR Policy) Rules, 2014", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "National Company Law Tribunal Rules, 2016", link: "https://www.mca.gov.in/" },
  { category: "Companies & Corporate", name: "National Company Law Appellate Tribunal Rules, 2016", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Rules, 2009", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP (Winding Up and Dissolution) Rules, 2012", link: "https://www.mca.gov.in/" },
  { category: "FEMA & RBI", name: "Foreign Exchange Management (Non-Debt Instruments) Rules, 2019", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "Foreign Exchange Management (Debt Instruments) Regulations", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "Overseas Investment Rules, 2022", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "Overseas Investment Regulations, 2022", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "External Commercial Borrowings Framework", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "Master Direction – Reporting under FEMA", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "Master Direction – Foreign Investment in India", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "Master Direction – Liberalised Remittance Scheme", link: "https://www.rbi.org.in/" },
  { category: "FEMA & RBI", name: "Master Direction – KYC", link: "https://www.rbi.org.in/" },
  { category: "SEBI", name: "SEBI (AIF) Regulations, 2012", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (Portfolio Managers) Regulations, 2020", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (Investment Advisers) Regulations, 2013", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (Research Analysts) Regulations, 2014", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (LODR) Regulations, 2015", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (PIT) Regulations, 2015", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (SAST) Regulations, 2011", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (ICDR) Regulations, 2018", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (Issue and Listing of Non-Convertible Securities) Regulations, 2021", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (Merchant Bankers) Regulations, 1992", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (Depositories and Participants) Regulations, 2018", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (Mutual Funds) Regulations, 1996", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (REIT) Regulations, 2014", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (InvIT) Regulations, 2014", link: "https://www.sebi.gov.in/" },
  { category: "SEBI", name: "SEBI (FPI) Regulations, 2019", link: "https://www.sebi.gov.in/" },
  { category: "Insolvency & IBC", name: "IBBI (Insolvency Resolution Process for Corporate Persons) Regulations, 2016", link: "https://www.ibbi.gov.in/" },
  { category: "Insolvency & IBC", name: "IBBI (Liquidation Process) Regulations, 2016", link: "https://www.ibbi.gov.in/" },
  { category: "Insolvency & IBC", name: "IBBI (Voluntary Liquidation Process) Regulations, 2017", link: "https://www.ibbi.gov.in/" },
  { category: "Insolvency & IBC", name: "IBBI (Insolvency Professionals) Regulations, 2016", link: "https://www.ibbi.gov.in/" },
  { category: "Insolvency & IBC", name: "IBBI (Valuation) Rules, 2017", link: "https://www.ibbi.gov.in/" },
  { category: "Labour & Employment", name: "Code on Wages Rules", link: "https://www.epfindia.gov.in/" },
  { category: "Labour & Employment", name: "Occupational Safety Rules", link: "https://www.epfindia.gov.in/" },
  { category: "Labour & Employment", name: "EPF Scheme, 1952", link: "https://www.epfindia.gov.in/" },
  { category: "Labour & Employment", name: "Employees' Pension Scheme, 1995", link: "https://www.epfindia.gov.in/" },
  { category: "Labour & Employment", name: "ESI (General) Regulations, 1950", link: "https://www.epfindia.gov.in/" },
  { category: "NGO / CSR / FCRA", name: "Foreign Contribution (Regulation) Rules, 2011", link: "https://fcraonline.nic.in/" },
  { category: "NGO / CSR / FCRA", name: "Companies (CSR Policy) Rules, 2014 — CSR", link: "https://fcraonline.nic.in/" },
  { category: "NGO / CSR / FCRA", name: "CSR-1 Registration Framework", link: "https://fcraonline.nic.in/" },
  { category: "Accounting & Audit", name: "Indian Accounting Standards (Ind AS)", link: "https://www.icai.org/" },
  { category: "Accounting & Audit", name: "Accounting Standards (AS)", link: "https://www.icai.org/" },
  { category: "Accounting & Audit", name: "Standards on Auditing (SA)", link: "https://www.icai.org/" },
  { category: "Accounting & Audit", name: "Standards on Quality Management (SQM)", link: "https://www.icai.org/" },
  { category: "Accounting & Audit", name: "Schedule III to Companies Act, 2013", link: "https://www.icai.org/" },
  { category: "Accounting & Audit", name: "Guidance Notes issued by ICAI", link: "https://www.icai.org/" },
];

export const forms: RepoItem[] = [
  { category: "Income Tax", name: "ITR-1", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "ITR-2", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "ITR-3", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "ITR-4", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "ITR-5", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "ITR-6", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "ITR-7", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CA", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CB", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CD", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CEB", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 10B", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 10BB", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 29B (MAT)", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 56F", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 56FF", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 67", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 15CA", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 15CB", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 10F", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 10FA", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 10FB", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CEAA", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CEAB", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CEAC", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CEAD", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 3CEAE", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 35", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 36", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 34F", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "Form 26AS", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "AIS", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Income Tax", name: "TIS", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "GST", name: "GST REG-01", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST REG-03", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST REG-06", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST REG-16", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-1", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-3B", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-4", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-5", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-6", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-7", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-8", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-9", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GSTR-9C", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST RFD-01", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST RFD-08", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST PMT-06", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST DRC-01", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST DRC-03", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "GST DRC-07", link: "https://taxbykk.com/gst-forms/" },
  { category: "GST", name: "LUT (RFD-11)", link: "https://taxbykk.com/gst-forms/" },
  { category: "ROC", name: "SPICe+", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "AGILE-PRO", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "INC-9", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "INC-20A", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "AOC-4", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "AOC-4 XBRL", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "MGT-7", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "MGT-7A", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "ADT-1", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "DIR-3", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "DIR-3 KYC", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "DIR-12", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "PAS-3", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "SH-7", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "MGT-14", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "CHG-1", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "CHG-4", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "CHG-9", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "INC-22", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "INC-24", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "INC-28", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "STK-2", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "DPT-3", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "MSME-1", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "BEN-2", link: "https://www.mca.gov.in/" },
  { category: "ROC", name: "CSR-2", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "FiLLiP", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Form 3", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Form 4", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Form 5", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Form 8", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Form 11", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Form 24", link: "https://www.mca.gov.in/" },
  { category: "LLP", name: "LLP Form 27", link: "https://www.mca.gov.in/" },
  { category: "FEMA / RBI", name: "FC-GPR", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "FC-TRS", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "LLP-I", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "LLP-II", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "FLA Return", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "Form FC", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "Form OPI", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "ECB-2 Return", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "APR", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "DI", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "FEMA / RBI", name: "CN", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "SEBI", name: "Form A (AIF Registration)", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "PPM Filing", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "Material Change Filing", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "Scheme Filing", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "Winding-up Filing", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "PMS Registration Application", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "PMS Net Worth Certificate", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "PMS Compliance Reporting Forms", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "IA Registration Application", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "IA Annual Compliance Report", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "RA Registration Application", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "SEBI", name: "RA Annual Reporting", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
  { category: "Trust / NGO", name: "Form 10A (Trust)", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "Form 10AB (Trust)", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "Form 10BD (Trust)", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "Form 10BE (Trust)", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "CSR-1", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "FC-3A", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "FC-3B", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "FC-3C", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "FC-4", link: "https://incometaxindia.gov.in/" },
  { category: "Trust / NGO", name: "FC-6", link: "https://incometaxindia.gov.in/" },
  { category: "Labour Law", name: "PF Form 5A", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "PF Form 10C", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "PF Form 10D", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "PF Form 13", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "PF Form 19", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "ESIC Employer Registration", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "ESIC Employee Registration", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "Gratuity Form F", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "Gratuity Form I", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "Gratuity Form J", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "Labour Law", name: "Gratuity Form K", link: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
  { category: "IBC / NCLT", name: "NCLT-1", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "NCLT-6", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "NCLT-9", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "CIRP Form A", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "CIRP Form B", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "CIRP Form C", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "CIRP Form D", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "CIRP Form E", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "IBC / NCLT", name: "CIRP Form F", link: "https://www.resurgentrp.com/ibc-forms" },
  { category: "Startup & Funding", name: "Startup India Recognition Application", link: "https://www.startupindia.gov.in/" },
  { category: "Startup & Funding", name: "Angel Tax Exemption Application", link: "https://www.startupindia.gov.in/" },
  { category: "Startup & Funding", name: "ESOP Grant Documentation", link: "https://www.startupindia.gov.in/" },
  { category: "Startup & Funding", name: "SAFE Note Template", link: "https://www.startupindia.gov.in/" },
  { category: "Startup & Funding", name: "Convertible Note Template", link: "https://www.startupindia.gov.in/" },
  { category: "Valuation & Certification", name: "Valuation Report Format", link: "https://ibbi.gov.in/en/registered-valuers" },
  { category: "Valuation & Certification", name: "Net Worth Certificate", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Valuation & Certification", name: "Turnover Certificate", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Valuation & Certification", name: "Utilisation Certificate", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Valuation & Certification", name: "CA Certificate Format", link: "https://www.incometaxindia.gov.in/income-tax-forms" },
  { category: "Valuation & Certification", name: "FEMA Certificate Format", link: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
  { category: "Valuation & Certification", name: "SEBI Certificate Format", link: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
];

/** Curated official / authoritative form-source lists, surfaced at the top of
 *  the Forms page so users jump straight to the live source instead of a portal
 *  root. URLs are the firm's confirmed references (client update, 12 Jun 2026). */
export interface FormSource {
  group: string;
  links: { label: string; url: string }[];
}

export const formSources: FormSource[] = [
  {
    group: "Income Tax",
    links: [
      { label: "Income Tax Forms — incometaxindia.gov.in", url: "https://www.incometaxindia.gov.in/income-tax-forms" },
    ],
  },
  {
    group: "GST",
    links: [
      { label: "GST Forms — TaxByKK", url: "https://taxbykk.com/gst-forms/" },
      { label: "GST Forms list (PDF) — GST portal", url: "https://tutorial.gst.gov.in/downloads/news/Forms_Available_Update_03132020.pdf" },
      { label: "CGST / GST Forms — CACJSNanda", url: "https://cacjsnanda.com/resources/Forms/CGST_Forms/GST_Forms/GST_Forms.aspx" },
    ],
  },
  {
    group: "SEBI",
    links: [
      { label: "SEBI Formats (PDF)", url: "https://www.sebi.gov.in/sebi_data/commondocs/apr-2018/Format_2016_p.pdf" },
    ],
  },
  {
    group: "RBI / NBFC / FEMA",
    links: [
      { label: "RBI Forms — rbi.org.in", url: "https://www.rbi.org.in/Scripts/BS_ViewForms.aspx" },
      { label: "NBFC Forms — MSN Associates", url: "https://www.msnassociates.in/resources/Forms/NBFC_Forms/NBFC_Forms.aspx" },
      { label: "PRAVAAH Forms list (PDF) — FIDC India", url: "https://www.fidcindia.org.in/wp-content/uploads/2025/05/LIST-OF-PRAVAAH-FORMS-28-04-25.pdf" },
    ],
  },
  {
    group: "Labour Law",
    links: [
      { label: "Labour Law Forms — Advocatekhoj", url: "https://www.advocatekhoj.com/library/legalforms/formsfor/index.php?Fno=labourlaw1.php" },
    ],
  },
  {
    group: "Insolvency & IBC",
    links: [
      { label: "IBC Forms — Resurgent", url: "https://www.resurgentrp.com/ibc-forms" },
      { label: "IBBI Rules & Regulations", url: "https://ibbi.gov.in/legal-framework/rules" },
    ],
  },
];

export const quickLinks = [
  {
    group: "Direct Tax",
    links: [
      { label: "Income-tax e-filing", href: "https://www.incometax.gov.in/" },
      { label: "CBDT", href: "https://incometaxindia.gov.in/" },
      { label: "TRACES", href: "https://www.tdscpc.gov.in/" },
    ],
  },
  {
    group: "Indirect Tax",
    links: [
      { label: "GST portal (GSTN)", href: "https://www.gst.gov.in/" },
      { label: "CBIC", href: "https://www.cbic.gov.in/" },
      { label: "CBIC-GST", href: "https://cbic-gst.gov.in/" },
      { label: "ICEGATE (Customs)", href: "https://www.icegate.gov.in/" },
      { label: "DGFT", href: "https://www.dgft.gov.in/" },
    ],
  },
  {
    group: "Corporate & Regulatory",
    links: [
      { label: "MCA21", href: "https://www.mca.gov.in/" },
      { label: "RBI", href: "https://www.rbi.org.in/" },
      { label: "RBI FIRMS (FDI)", href: "https://firms.rbi.org.in/" },
      { label: "SEBI", href: "https://www.sebi.gov.in/" },
      { label: "IBBI", href: "https://www.ibbi.gov.in/" },
      { label: "NCLT", href: "https://www.nclt.gov.in/" },
      { label: "IRDAI", href: "https://www.irdai.gov.in/" },
    ],
  },
  {
    group: "Labour, NGO & Other",
    links: [
      { label: "DPIIT / Startup India", href: "https://www.startupindia.gov.in/" },
      { label: "EPFO", href: "https://www.epfindia.gov.in/" },
      { label: "ESIC", href: "https://www.esic.gov.in/" },
      { label: "FCRA Online", href: "https://fcraonline.nic.in/" },
      { label: "IP India", href: "https://ipindia.gov.in/" },
      { label: "ICAI", href: "https://www.icai.org/" },
    ],
  },
];
